---
- name: Undo advanced playbook
  hosts: serverc.lab.example.com
  vars_files: users.yml

  tasks:
    - name: Remove custom motd
      ansible.builtin.file:
        path: /etc/motd
        state: absent
      become: true

    - name: Remove users
      ansible.builtin.user:
        name: "{{ item.name }}"
        state: absent 
      loop: "{{ users }}"
      become: true
